### CONFIGURATION OPTIONS (NUA TODO: add all configuration options)
##    world_name: 
##      training_garden_static_0
##      training_garden_dynamic_0
##      validation
##      real

## World Parameters
world_name: "real"
world_frame_name: "map"

## Goal Parameters
goal_msg: ""
n_goal: 1

goal1_x: -2.0
goal1_y: -6.0
goal1_z: 0.0
goal1_yaw: -0.7854 # approx -Pi / 4

#goal2_x: -15.0
#goal2_y: -15.0
#goal2_z: 1.0
#goal2_yaw: -0.7854 # approx -Pi / 4

## Robot Parameters
n_robot: 1
robot_name: "jackal"
robot_model: ""
robot_frame_name: "base_link"

robot_bbx_x_min: -0.5
robot_bbx_x_max: 0.5
robot_bbx_y_min: -0.4
robot_bbx_y_max: 0.4
robot_bbx_z_min: -0.0
robot_bbx_z_max: 0.6

robot_max_lat_velo: 1.0
robot_max_lat_acc: 1.0
robot_max_yaw_velo: 2.0
robot_max_yaw_acc: 2.0

robot_init_pos_x: 0.0                
robot_init_pos_y: 0.0                 
robot_init_pos_z: 0.0                  
robot_init_yaw: 0.0

robot_odometry_msg: "/jackal_velocity_controller/odom"
robot_pose_control_msg: ""
robot_velo_control_msg: "/jackal_velocity_controller/cmd_vel"