## Testing Parameters

mode: "testing"
data_path: "/home/akmandor/catkin_ws/src/mp_algorithms/tentabot/data/testing/"
#initial_trained_model_path: "/home/akmandor/catkin_ws/src/mp_algorithms/tentabot/data/training/20210911_223347_PPO_tentabot/"
initial_trained_model_path: "/home/akmandor/catkin_ws/src/mp_algorithms/tentabot/data/training/Tentabot_FC/20210914_095714_PPO_tentabot/"

# SIMULATION: testing_lvl_1
# EXPERIMENT: 
world_name: "testing_lvl_7"

# SIMULATION: /turtlebot0/cmd_vel
# EXPERIMENT: /cmd_vel_mux/input/teleop
velocity_control_msg: "/turtlebot0/cmd_vel"

# SIMULATION: /turtlebot0/odom
# EXPERIMENT: /odom
odometry_msg: "/turtlebot0/odom"

goal_status_msg: "/turtlebot0/goal_reaching_status"
testing_timesteps: 2000
max_testing_episodes: 10