## Robot Parameters
local_map_msg: "/octomap_tentabot"

# NOTE: Expected to be available in ROS paremeter server
#       by config files task_nav, map_utility
#world_frame_name: ""
#n_goal: 1
#goal1_x: 0.0
#goal1_y: 0.0
#goal1_z: 1.0
#goal1_yaw: 0.0
#world_name: ""
#robot_name: ""
#robot_frame_name: ""
#robot_bbx_x_min: 0.0
#robot_bbx_x_max: 0.0
#robot_bbx_y_min: 0.0
#robot_bbx_y_max: 0.0
#robot_bbx_z_min: 0.0
#robot_bbx_z_max: 0.0
#robot_max_lat_velo: 0.0
#robot_max_lat_acc: 0.0
#robot_max_yaw_velo: 0.0
#robot_max_yaw_acc: 0.0
#robot_odometry_msg: "/firefly/odometry_sensor1/odometry"
#robot_pose_control_msg: "/firefly/command/pose"
#robot_velo_control_msg: ""

## Process Parameters
visu_flag: true 
time_limit: 90 
dt: 0.1 
goal_close_threshold: 0.5
ground_collision_flag: true
ground_collision_threshold: 0.1
nav_data_path: "dataset/heuristic/firefly/"
drl_service_flag: false

## Trajectory Sampling Parameters
trajectory_sampling_dataset_path: "dataset/trajectory_sampling/firefly/"
tlen: 10
tsamp_cnt: 25

trajectory_gen_type: "geometric"
tyaw: 0.9 
tpitch: 0.6
tyaw_cnt: 21
tpitch_cnt: 11

#trajectory_gen_type: "kinematic"
ttime: 10
lat_velo_samp_cnt: 1
ang_velo_samp_cnt: 1

## Offline Tuning Parameters
trajectory_data_path: "dataset/trajectory_sampling/firefly/20220323_111503/"
max_occupancy_belief_value: 100
sweight_max: 1 
sweight_scale: 10 
egrid_vdim: 0.1 

pdist_x_min: -0.3
pdist_x_max: 0.3
pdist_y_min: -0.3
pdist_y_max: 0.3
pdist_z_min: -0.4
pdist_z_max: 0.3

sdist_x_min: -0.6
sdist_x_max: 0.6
sdist_y_min: -0.6
sdist_y_max: 0.6
sdist_z_min: -0.8
sdist_z_max: 0.6

## Online tuning Parameters
tbin_obs_cnt_threshold: 1 
crash_dist_scale: 0.3
occupancy_scale: 2
close_scale: 30
smooth_scale: 5

### DRL Parameters 
### NOTE: Be sure that -> drl_service_flag: true
### TODO: Add robot and task in openai_ros!