task_and_robot_environment_name: 'TurtleBot3World-v1'
world_name: "training_4robot3D1P"
number_of_robots: 4
ros_ws_abspath: "/home/akmandor/devel_ws"
running_step: 0.04 # amount of time the control will be executed
pos_step: 0.016     # increment in position for each command

## Robot
robot0_init_pos_x: 0.8866   #NUA NOTE: Sync with the gazebo launch file!
robot0_init_pos_y: 0.24     #NUA NOTE: Sync with the gazebo launch file!
robot0_init_pos_z: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot0_init_rot_x: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot0_init_rot_y: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot0_init_rot_z: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot0_init_rot_w: 1.0      #NUA NOTE: Sync with the gazebo launch file!

robot1_init_pos_x: 1.18     #NUA NOTE: Sync with the gazebo launch file!
robot1_init_pos_y: 12.13    #NUA NOTE: Sync with the gazebo launch file!
robot1_init_pos_z: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot1_init_rot_x: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot1_init_rot_y: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot1_init_rot_z: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot1_init_rot_w: 1.0      #NUA NOTE: Sync with the gazebo launch file!

robot2_init_pos_x: -10.085  #NUA NOTE: Sync with the gazebo launch file!
robot2_init_pos_y: 12.15    #NUA NOTE: Sync with the gazebo launch file!
robot2_init_pos_z: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot2_init_rot_x: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot2_init_rot_y: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot2_init_rot_z: 1.0      #NUA NOTE: Sync with the gazebo launch file!
robot2_init_rot_w: 0.001    #NUA NOTE: Sync with the gazebo launch file!

robot3_init_pos_x: -11.0    #NUA NOTE: Sync with the gazebo launch file!
robot3_init_pos_y: -0.03    #NUA NOTE: Sync with the gazebo launch file!
robot3_init_pos_z: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot3_init_rot_x: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot3_init_rot_y: 0.0      #NUA NOTE: Sync with the gazebo launch file!
robot3_init_rot_z: 1.0      #NUA NOTE: Sync with the gazebo launch file!
robot3_init_rot_w: 0.001    #NUA NOTE: Sync with the gazebo launch file!

#qlearn parameters
alpha: 0.1
gamma: 0.7
epsilon: 0.9
epsilon_discount: 0.999
nepisodes: 2
nsteps: 250
running_step: 0.06 # Time for each step