# https://husarion.com/tutorials/ros-tutorials/7-path-planning

# AUTHOR: Husarion
#         Gary M. Lvov (GML)
# E-MAIL: lvov.g@northeastern.edu

obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
map_topic: ROSbot0/map
subscribe_to_updates: true
global_frame: ROSbot0/map
robot_base_frame: ROSbot0/base_link
always_send_full_costmap: true
static_layer:
    map_topic: ROSbot0/map
    subscribe_to_updates: true
plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: ROSbot0/laser, data_type: LaserScan, topic: ROSbot0/scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 5.0, obstacle_range: 6.0, raytrace_range: 8.5}